apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/tilt-gotest/
patches:
  - path: patch.yaml
images:
- name: tilt-gotest:1.0
  newName: tilt-gotest
  newTag: "1.0"
